#:kivy 1.0.8

<Widget>:
    canvas.after:
        Line:
            rectangle: self.x+1,self.y+1,self.width-1,self.height-1
            dash_offset: 5
            dash_length: 3

<PasswordScreen>
    user_label: userlabel
    pl: passwordlabel
    password_input: password_input
    user_input: user_input

    Label:
        text: 'User'
        font_size:self.height * .8
        size_hint: .4, .15
        pos: 5, self.parent.top - self.height - 5
        halign: 'center'
        valign: 'middle'
        text_size: self.size
        id: userlabel
    TextInput:
        id: user_input
        font_size:self.height * .7
        valign: 'middle'
        multiline: False
        size_hint: 0.58, .15
        x: self.parent.width - self.width - 5
        center_y: self.parent.user_label.center_y
        padding: 6
        focus: True
        on_text_validate: root.password_input.focus = True

        #left, top, right, bottom


    Label:
        text: 'Password'
        size_hint: .4, .15
        x: 5
        top: self.parent.user_label.y - 5
        font_size:self.height * .8
        halign: 'center'
        valign: 'middle'
        id: passwordlabel
        #text_size: self.size

    TextInput:
        id: password_input
        #font_size:self.height * .8
        font_size:self.height * .7
        multiline: False
        size_hint: .58, .15
        x: self.parent.width - self.width - 5
        center_y: self.parent.pl.center_y
        padding: 6
        #left, top, right, bottom
    Button:
        text: 'Login'
        size_hint: .3, .15
        center_x: self.parent.pl.center_x
        center_y: self.parent.pl.y / 2
        font_size:self.height * .8
        on_press: root.login_request()

    Button:
        text: 'Exit'
        size_hint: .3, .15
        center_x: self.parent.password_input.center_x
        center_y: self.parent.pl.y/2
        font_size: self.height * .8

